// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proyecto_arcos

#include "ui.h"

void enviarProporcional(lv_event_t * e)
{
	// Your code here
}

void enviarIntegral(lv_event_t * e)
{
	// Your code here
}

void enviarDerivatico(lv_event_t * e)
{
	// Your code here
}

void enviarDerivativo(lv_event_t * e)
{
	// Your code here
}

void resetearconstantes(lv_event_t * e)
{
	// Your code here
}

void enviarSetPoint(lv_event_t * e)
{
	// Your code here
}

void encendermotorizquierdo(lv_event_t * e)
{
	// Your code here
}

void encendermotorderecho(lv_event_t * e)
{
	// Your code here
}
