// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proyecto_arcos

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x8300A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen6, lv_color_hex(0x2D002E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen6, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panel8, 435);
    lv_obj_set_height(ui_Panel8, 62);
    lv_obj_set_x(ui_Panel8, -140);
    lv_obj_set_y(ui_Panel8, -186);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x00105C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel8, lv_color_hex(0x0D00F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel8, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -140);
    lv_obj_set_y(ui_Label30, -186);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Test de Motores");
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Screen6);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 727);
    lv_obj_set_height(ui_Container4, 334);
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, 41);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switchizquierda = lv_switch_create(ui_Screen6);
    lv_obj_set_width(ui_Switchizquierda, 288);
    lv_obj_set_height(ui_Switchizquierda, 125);
    lv_obj_set_x(ui_Switchizquierda, -191);
    lv_obj_set_y(ui_Switchizquierda, 122);
    lv_obj_set_align(ui_Switchizquierda, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switchizquierda, lv_color_hex(0xFF0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switchizquierda, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switchizquierda, lv_color_hex(0x4E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switchizquierda, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switchizquierda, lv_color_hex(0x0BFF00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switchizquierda, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switchizquierda, lv_color_hex(0x096000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switchizquierda, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switchizquierda, lv_color_hex(0xCBCBCB), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switchizquierda, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switchizquierda, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switchizquierda, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Switchderecha = lv_switch_create(ui_Screen6);
    lv_obj_set_width(ui_Switchderecha, 288);
    lv_obj_set_height(ui_Switchderecha, 125);
    lv_obj_set_x(ui_Switchderecha, 188);
    lv_obj_set_y(ui_Switchderecha, 122);
    lv_obj_set_align(ui_Switchderecha, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switchderecha, lv_color_hex(0xFF0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switchderecha, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Switchderecha, lv_color_hex(0x4E0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Switchderecha, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switchderecha, lv_color_hex(0x0BFF00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switchderecha, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_Switchderecha, lv_color_hex(0x096000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_dir(ui_Switchderecha, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switchderecha, lv_color_hex(0xCBCBCB), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switchderecha, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switchderecha, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switchderecha, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Panel6 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panel6, 9);
    lv_obj_set_height(ui_Panel6, 314);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, 43);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image8, &ui_img_balancin_11zon_11zon_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 495
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, 1);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 350);

    ui_Image9 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image9, &ui_img_engra_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 78
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 78
    lv_obj_set_x(ui_Image9, 37);
    lv_obj_set_y(ui_Image9, -38);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image9, 400);

    ui_Image10 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image10, &ui_img_engra_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 78
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 78
    lv_obj_set_x(ui_Image10, -31);
    lv_obj_set_y(ui_Image10, -54);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image10, 400);

    ui_Button8 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_Button8, 172);
    lv_obj_set_height(ui_Button8, 60);
    lv_obj_set_x(ui_Button8, 271);
    lv_obj_set_y(ui_Button8, -184);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x00C911), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button8, lv_color_hex(0x004903), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button8, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 270);
    lv_obj_set_y(ui_Label31, -185);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Atras");
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Switchizquierda, ui_event_Switchizquierda, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switchderecha, ui_event_Switchderecha, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);

}
