// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proyecto_arcos

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000154), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel3, 489);
    lv_obj_set_height(ui_Panel3, 66);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, -184);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x00105C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel3, lv_color_hex(0x0D00F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 3);
    lv_obj_set_y(ui_Label4, -183);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Menu Principal");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen3);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 355);
    lv_obj_set_height(ui_Container1, 320);
    lv_obj_set_x(ui_Container1, -193);
    lv_obj_set_y(ui_Container1, 44);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x6100A2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPIDconstantes = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_PanelPIDconstantes, 325);
    lv_obj_set_height(ui_PanelPIDconstantes, 138);
    lv_obj_set_x(ui_PanelPIDconstantes, -191);
    lv_obj_set_y(ui_PanelPIDconstantes, -28);
    lv_obj_set_align(ui_PanelPIDconstantes, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelPIDconstantes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPIDconstantes, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelPIDconstantes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelPIDconstantes, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelPIDconstantes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_PanelPIDconstantes);
    lv_img_set_src(ui_Image4, &ui_img_pid_11zon_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -83);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 240);

    ui_BotonPIDconstante = lv_btn_create(ui_PanelPIDconstantes);
    lv_obj_set_width(ui_BotonPIDconstante, 142);
    lv_obj_set_height(ui_BotonPIDconstante, 50);
    lv_obj_set_x(ui_BotonPIDconstante, 71);
    lv_obj_set_y(ui_BotonPIDconstante, -1);
    lv_obj_set_align(ui_BotonPIDconstante, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BotonPIDconstante, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BotonPIDconstante, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BotonPIDconstante, lv_color_hex(0x87007F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BotonPIDconstante, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_PanelPIDconstantes);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 70);
    lv_obj_set_y(ui_Label3, -1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Kp Ki Kd");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelVisualizar = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_PanelVisualizar, 325);
    lv_obj_set_height(ui_PanelVisualizar, 138);
    lv_obj_set_x(ui_PanelVisualizar, 177);
    lv_obj_set_y(ui_PanelVisualizar, 146);
    lv_obj_set_align(ui_PanelVisualizar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVisualizar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelVisualizar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelVisualizar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelVisualizar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelVisualizar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_PanelVisualizar);
    lv_img_set_src(ui_Image6, &ui_img_realtime_11zon_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -83);
    lv_obj_set_y(ui_Image6, 0);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 240);

    ui_BotonVisuelizar = lv_btn_create(ui_PanelVisualizar);
    lv_obj_set_width(ui_BotonVisuelizar, 142);
    lv_obj_set_height(ui_BotonVisuelizar, 50);
    lv_obj_set_x(ui_BotonVisuelizar, 71);
    lv_obj_set_y(ui_BotonVisuelizar, -1);
    lv_obj_set_align(ui_BotonVisuelizar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BotonVisuelizar, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BotonVisuelizar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BotonVisuelizar, lv_color_hex(0x87007F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BotonVisuelizar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_PanelVisualizar);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 70);
    lv_obj_set_y(ui_Label6, -1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Visualizar");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTestear = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_PanelTestear, 325);
    lv_obj_set_height(ui_PanelTestear, 138);
    lv_obj_set_x(ui_PanelTestear, 195);
    lv_obj_set_y(ui_PanelTestear, 156);
    lv_obj_set_align(ui_PanelTestear, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelTestear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTestear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTestear, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTestear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTestear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_PanelTestear);
    lv_img_set_src(ui_Image5, &ui_img_herramientas_11zon_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -83);
    lv_obj_set_y(ui_Image5, 0);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 300);

    ui_Botontestear = lv_btn_create(ui_PanelTestear);
    lv_obj_set_width(ui_Botontestear, 142);
    lv_obj_set_height(ui_Botontestear, 50);
    lv_obj_set_x(ui_Botontestear, 71);
    lv_obj_set_y(ui_Botontestear, -1);
    lv_obj_set_align(ui_Botontestear, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Botontestear, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Botontestear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Botontestear, lv_color_hex(0x87007F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Botontestear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_PanelTestear);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 70);
    lv_obj_set_y(ui_Label5, -1);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Testear");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMasInfo = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_PanelMasInfo, 325);
    lv_obj_set_height(ui_PanelMasInfo, 138);
    lv_obj_set_x(ui_PanelMasInfo, 199);
    lv_obj_set_y(ui_PanelMasInfo, -33);
    lv_obj_set_align(ui_PanelMasInfo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelMasInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelMasInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMasInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelMasInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelMasInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_PanelMasInfo);
    lv_img_set_src(ui_Image7, &ui_img_lista_11zon_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -83);
    lv_obj_set_y(ui_Image7, 0);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 240);

    ui_BotonMasInfo = lv_btn_create(ui_PanelMasInfo);
    lv_obj_set_width(ui_BotonMasInfo, 142);
    lv_obj_set_height(ui_BotonMasInfo, 50);
    lv_obj_set_x(ui_BotonMasInfo, 71);
    lv_obj_set_y(ui_BotonMasInfo, -1);
    lv_obj_set_align(ui_BotonMasInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BotonMasInfo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BotonMasInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BotonMasInfo, lv_color_hex(0x87007F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BotonMasInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_PanelMasInfo);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 70);
    lv_obj_set_y(ui_Label7, -1);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Mas Info");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label8, 378);
    lv_obj_set_height(ui_Label8, 320);
    lv_obj_set_x(ui_Label8, 195);
    lv_obj_set_y(ui_Label8, 45);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8,
                      "Kp Ki Kp: Puedes cambiar las constantes que vienen por defecto.\n\nVisualizar: Se puede apreciar graficamente como el sistema se acerca al set point.\n\nTestear: Se puede controlar el encendido de cada motor para verificar su funcionamiento.");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BotonPIDconstante, ui_event_BotonPIDconstante, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BotonVisuelizar, ui_event_BotonVisuelizar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Botontestear, ui_event_Botontestear, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BotonMasInfo, ui_event_BotonMasInfo, LV_EVENT_ALL, NULL);

}
