// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proyecto_arcos

#ifndef _PROYECTO_ARCOS_UI_H
#define _PROYECTO_ARCOS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

void girarbalancin_Animation(lv_obj_t * TargetObject, int delay);
void girarbalancin2_Animation(lv_obj_t * TargetObject, int delay);
void girarbalancin3_Animation(lv_obj_t * TargetObject, int delay);
void girarengra_Animation(lv_obj_t * TargetObject, int delay);
void girarengra2_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_PanelPIDconstantes;
extern lv_obj_t * ui_Image4;
void ui_event_BotonPIDconstante(lv_event_t * e);
extern lv_obj_t * ui_BotonPIDconstante;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_PanelVisualizar;
extern lv_obj_t * ui_Image6;
void ui_event_BotonVisuelizar(lv_event_t * e);
extern lv_obj_t * ui_BotonVisuelizar;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_PanelTestear;
extern lv_obj_t * ui_Image5;
void ui_event_Botontestear(lv_event_t * e);
extern lv_obj_t * ui_Botontestear;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_PanelMasInfo;
extern lv_obj_t * ui_Image7;
void ui_event_BotonMasInfo(lv_event_t * e);
extern lv_obj_t * ui_BotonMasInfo;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_SliderProporcional;
extern lv_obj_t * ui_SliderIntegral;
extern lv_obj_t * ui_SliderDerivativo;
void ui_event_ButtonProporcional(lv_event_t * e);
extern lv_obj_t * ui_ButtonProporcional;
extern lv_obj_t * ui_Label10;
void ui_event_ButtonIntegral(lv_event_t * e);
extern lv_obj_t * ui_ButtonIntegral;
void ui_event_ButtonDerivativo(lv_event_t * e);
extern lv_obj_t * ui_ButtonDerivativo;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_LabelProporcional;
extern lv_obj_t * ui_LabelIntegral;
extern lv_obj_t * ui_LabelDerivativo;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label21;
void ui_event_ButtonResetear(lv_event_t * e);
extern lv_obj_t * ui_ButtonResetear;
extern lv_obj_t * ui_Label17;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_ChartGrafica;
extern lv_obj_t * ui_SlidersetPoint;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_LabelValorSetPoint;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label28;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label29;
void ui_event_ButtonSetPoint(lv_event_t * e);
extern lv_obj_t * ui_ButtonSetPoint;
extern lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Container4;
void ui_event_Switchizquierda(lv_event_t * e);
extern lv_obj_t * ui_Switchizquierda;
void ui_event_Switchderecha(lv_event_t * e);
extern lv_obj_t * ui_Switchderecha;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label31;
// CUSTOM VARIABLES

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
void ui_event_Screen7(lv_event_t * e);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label27;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_usc_11zon_png);    // assets/logo_usc_11zon.png
LV_IMG_DECLARE(ui_img_triangulo_11zon_11zon_png);    // assets/triangulo_11zon_11zon.png
LV_IMG_DECLARE(ui_img_balancin_11zon_11zon_png);    // assets/balancin_11zon_11zon.png
LV_IMG_DECLARE(ui_img_pid_11zon_png);    // assets/PID_11zon.png
LV_IMG_DECLARE(ui_img_realtime_11zon_png);    // assets/realtime_11zon.png
LV_IMG_DECLARE(ui_img_herramientas_11zon_png);    // assets/herramientas_11zon.png
LV_IMG_DECLARE(ui_img_lista_11zon_png);    // assets/lista_11zon.png
LV_IMG_DECLARE(ui_img_engra_png);    // assets/engra.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
