// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proyecto_arcos

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void enviarProporcional(lv_event_t * e);
void enviarIntegral(lv_event_t * e);
void enviarDerivativo(lv_event_t * e);
void resetearconstantes(lv_event_t * e);
void enviarSetPoint(lv_event_t * e);
void encendermotorizquierdo(lv_event_t * e);
void encendermotorderecho(lv_event_t * e);


/// eventos para los sliders

/// pantalla 4
void ui_event_SliderProporcional(lv_event_t * e);
void ui_event_SliderIntegral(lv_event_t * e);
void ui_event_SliderDerivativo(lv_event_t * e);
void ui_event_SlidersetPoint(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
