// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proyecto_arcos

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x6600C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen5, lv_color_hex(0x350035), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartGrafica = lv_chart_create(ui_Screen5);
    lv_obj_set_width(ui_ChartGrafica, 554);
    lv_obj_set_height(ui_ChartGrafica, 353);
    lv_obj_set_x(ui_ChartGrafica, -76);
    lv_obj_set_y(ui_ChartGrafica, -54);
    lv_obj_set_align(ui_ChartGrafica, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartGrafica, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartGrafica, 50);
    lv_chart_set_range(ui_ChartGrafica, LV_CHART_AXIS_PRIMARY_Y, -50, 50);
    lv_chart_set_range(ui_ChartGrafica, LV_CHART_AXIS_SECONDARY_Y, -50, 50);
    lv_chart_set_div_line_count(ui_ChartGrafica, 11, 11);
    lv_chart_set_axis_tick(ui_ChartGrafica, LV_CHART_AXIS_PRIMARY_X, 0, 5, 10, 2, false, 50);
    lv_chart_set_axis_tick(ui_ChartGrafica, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartGrafica, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_ChartGrafica_series_1 = lv_chart_add_series(ui_ChartGrafica, lv_color_hex(0xEC0000),
                                                                       LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_ChartGrafica_series_1_array[] = { 0, 0, 0, 0, 0, 7, 16, 17, 16, 14, 10, 9, 8, 9, 10, 11, 12, 12, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 };
    ///lv_chart_set_ext_y_array(ui_ChartGrafica, ui_ChartGrafica_series_1, ui_ChartGrafica_series_1_array);
    lv_chart_series_t * ui_ChartGrafica_series_2 = lv_chart_add_series(ui_ChartGrafica, lv_color_hex(0x11E100),
                                                                       LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_ChartGrafica_series_2_array[] = { 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 };
    ///lv_chart_set_ext_y_array(ui_ChartGrafica, ui_ChartGrafica_series_2, ui_ChartGrafica_series_2_array);
    lv_obj_set_style_bg_color(ui_ChartGrafica, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartGrafica, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ChartGrafica, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartGrafica, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_ChartGrafica, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartGrafica, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ChartGrafica, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChartGrafica, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChartGrafica, &lv_font_montserrat_18, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_SlidersetPoint = lv_slider_create(ui_Screen5);
    lv_slider_set_range(ui_SlidersetPoint, -45, 45);
    lv_slider_set_value(ui_SlidersetPoint, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SlidersetPoint) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SlidersetPoint, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_SlidersetPoint, 589);
    lv_obj_set_height(ui_SlidersetPoint, 36);
    lv_obj_set_x(ui_SlidersetPoint, -89);
    lv_obj_set_y(ui_SlidersetPoint, 203);
    lv_obj_set_align(ui_SlidersetPoint, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SlidersetPoint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SlidersetPoint, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SlidersetPoint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SlidersetPoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SlidersetPoint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SlidersetPoint, lv_color_hex(0xC7DB00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SlidersetPoint, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SlidersetPoint, lv_color_hex(0xD10000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SlidersetPoint, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SlidersetPoint, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SlidersetPoint, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -259);
    lv_obj_set_y(ui_Label14, 162);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Ajustar Set Point");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 149);
    lv_obj_set_height(ui_Container2, 64);
    lv_obj_set_x(ui_Container2, 307);
    lv_obj_set_y(ui_Container2, 44);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelValorSetPoint = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelValorSetPoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValorSetPoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelValorSetPoint, 305);
    lv_obj_set_y(ui_LabelValorSetPoint, 45);
    lv_obj_set_align(ui_LabelValorSetPoint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValorSetPoint, "0");
    lv_obj_set_style_text_font(ui_LabelValorSetPoint, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 305);
    lv_obj_set_y(ui_Label23, -8);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "valor:");
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 352);
    lv_obj_set_y(ui_Label24, 34);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "°");
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 156);
    lv_obj_set_height(ui_Container3, 115);
    lv_obj_set_x(ui_Container3, 303);
    lv_obj_set_y(ui_Container3, -103);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label26, 187);
    lv_obj_set_height(ui_Label26, 101);
    lv_obj_set_x(ui_Label26, 317);
    lv_obj_set_y(ui_Label26, -167);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Visualizador en tiempo Real");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Panel2, 138);
    lv_obj_set_height(ui_Panel2, 6);
    lv_obj_set_x(ui_Panel2, 306);
    lv_obj_set_y(ui_Panel2, -120);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 304);
    lv_obj_set_y(ui_Label25, -140);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Angulo del sistema");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Panel7, 138);
    lv_obj_set_height(ui_Panel7, 6);
    lv_obj_set_x(ui_Panel7, 306);
    lv_obj_set_y(ui_Panel7, -64);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x03FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 271);
    lv_obj_set_y(ui_Label28, -80);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Set Point");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Button7, 129);
    lv_obj_set_height(ui_Button7, 49);
    lv_obj_set_x(ui_Button7, 308);
    lv_obj_set_y(ui_Button7, 198);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xBE00B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button7, lv_color_hex(0x690065), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button7, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 310);
    lv_obj_set_y(ui_Label29, 198);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Atras");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSetPoint = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonSetPoint, 122);
    lv_obj_set_height(ui_ButtonSetPoint, 50);
    lv_obj_set_x(ui_ButtonSetPoint, 308);
    lv_obj_set_y(ui_ButtonSetPoint, 128);
    lv_obj_set_align(ui_ButtonSetPoint, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSetPoint, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSetPoint, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonSetPoint, lv_color_hex(0x33C900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSetPoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonSetPoint, lv_color_hex(0x014900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ButtonSetPoint, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 306);
    lv_obj_set_y(ui_Label15, 129);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Enviar");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSetPoint, ui_event_ButtonSetPoint, LV_EVENT_ALL, NULL);

}
