// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Proyecto_arcos

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x5700A3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen4, lv_color_hex(0x3A0039), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen4, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Panel4, 435);
    lv_obj_set_height(ui_Panel4, 62);
    lv_obj_set_x(ui_Panel4, -118);
    lv_obj_set_y(ui_Panel4, -187);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x00105C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel4, lv_color_hex(0x0D00F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel4, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -121);
    lv_obj_set_y(ui_Label9, -186);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Constantes P&D");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderProporcional = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderProporcional, 60, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderProporcional) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderProporcional, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderProporcional, 505);
    lv_obj_set_height(ui_SliderProporcional, 38);
    lv_obj_set_x(ui_SliderProporcional, -120);
    lv_obj_set_y(ui_SliderProporcional, -53);
    lv_obj_set_align(ui_SliderProporcional, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderProporcional, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderProporcional, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SliderProporcional, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SliderProporcional, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderProporcional, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderProporcional, lv_color_hex(0xC7DB00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderProporcional, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderProporcional, lv_color_hex(0xD10000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderProporcional, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderProporcional, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderProporcional, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SliderIntegral = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderIntegral, 10, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderIntegral) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderIntegral, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderIntegral, 505);
    lv_obj_set_height(ui_SliderIntegral, 38);
    lv_obj_set_x(ui_SliderIntegral, -120);
    lv_obj_set_y(ui_SliderIntegral, 62);
    lv_obj_set_align(ui_SliderIntegral, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderIntegral, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderIntegral, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SliderIntegral, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SliderIntegral, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderIntegral, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderIntegral, lv_color_hex(0xC7DB00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderIntegral, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderIntegral, lv_color_hex(0xD10000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderIntegral, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderIntegral, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderIntegral, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SliderDerivativo = lv_slider_create(ui_Screen4);
    lv_slider_set_value(ui_SliderDerivativo, 90, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderDerivativo) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderDerivativo, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderDerivativo, 505);
    lv_obj_set_height(ui_SliderDerivativo, 38);
    lv_obj_set_x(ui_SliderDerivativo, -120);
    lv_obj_set_y(ui_SliderDerivativo, 172);
    lv_obj_set_align(ui_SliderDerivativo, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderDerivativo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderDerivativo, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SliderDerivativo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SliderDerivativo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderDerivativo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderDerivativo, lv_color_hex(0xC7DB00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderDerivativo, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderDerivativo, lv_color_hex(0xD10000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderDerivativo, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderDerivativo, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderDerivativo, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ButtonProporcional = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_ButtonProporcional, 122);
    lv_obj_set_height(ui_ButtonProporcional, 50);
    lv_obj_set_x(ui_ButtonProporcional, 214);
    lv_obj_set_y(ui_ButtonProporcional, -53);
    lv_obj_set_align(ui_ButtonProporcional, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonProporcional, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonProporcional, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonProporcional, lv_color_hex(0x33C900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonProporcional, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonProporcional, lv_color_hex(0x014900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ButtonProporcional, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 214);
    lv_obj_set_y(ui_Label10, -53);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Enviar");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonIntegral = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_ButtonIntegral, 122);
    lv_obj_set_height(ui_ButtonIntegral, 50);
    lv_obj_set_x(ui_ButtonIntegral, 214);
    lv_obj_set_y(ui_ButtonIntegral, 64);
    lv_obj_set_align(ui_ButtonIntegral, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonIntegral, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonIntegral, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonIntegral, lv_color_hex(0x33C900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonIntegral, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonIntegral, lv_color_hex(0x014900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ButtonIntegral, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonDerivativo = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_ButtonDerivativo, 122);
    lv_obj_set_height(ui_ButtonDerivativo, 50);
    lv_obj_set_x(ui_ButtonDerivativo, 214);
    lv_obj_set_y(ui_ButtonDerivativo, 172);
    lv_obj_set_align(ui_ButtonDerivativo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonDerivativo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonDerivativo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonDerivativo, lv_color_hex(0x33C900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDerivativo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonDerivativo, lv_color_hex(0x014900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ButtonDerivativo, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 214);
    lv_obj_set_y(ui_Label12, 62);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Enviar");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 214);
    lv_obj_set_y(ui_Label13, 172);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Enviar");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelProporcional = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelProporcional, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelProporcional, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelProporcional, 341);
    lv_obj_set_y(ui_LabelProporcional, -53);
    lv_obj_set_align(ui_LabelProporcional, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelProporcional, "3.0");
    lv_obj_set_style_text_font(ui_LabelProporcional, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIntegral = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelIntegral, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIntegral, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIntegral, 341);
    lv_obj_set_y(ui_LabelIntegral, 62);
    lv_obj_set_align(ui_LabelIntegral, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIntegral, "0.5");
    lv_obj_set_style_text_font(ui_LabelIntegral, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDerivativo = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelDerivativo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDerivativo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDerivativo, 341);
    lv_obj_set_y(ui_LabelDerivativo, 172);
    lv_obj_set_align(ui_LabelDerivativo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDerivativo, "4.5");
    lv_obj_set_style_text_font(ui_LabelDerivativo, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -245);
    lv_obj_set_y(ui_Label18, -102);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Proporcional Kp");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -285);
    lv_obj_set_y(ui_Label19, 18);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Integral Ki");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -262);
    lv_obj_set_y(ui_Label20, 132);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Derivativo Kd");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button1, 117);
    lv_obj_set_height(ui_Button1, 45);
    lv_obj_set_x(ui_Button1, 322);
    lv_obj_set_y(ui_Button1, -209);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xBE00B6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button1, lv_color_hex(0x690065), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 322);
    lv_obj_set_y(ui_Label21, -210);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Atras");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonResetear = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_ButtonResetear, 138);
    lv_obj_set_height(ui_ButtonResetear, 54);
    lv_obj_set_x(ui_ButtonResetear, 317);
    lv_obj_set_y(ui_ButtonResetear, -139);
    lv_obj_set_align(ui_ButtonResetear, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonResetear, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonResetear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonResetear, lv_color_hex(0xABAD00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonResetear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonResetear, lv_color_hex(0x3A3A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ButtonResetear, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 317);
    lv_obj_set_y(ui_Label17, -139);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Resetear");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonProporcional, ui_event_ButtonProporcional, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonIntegral, ui_event_ButtonIntegral, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonDerivativo, ui_event_ButtonDerivativo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonResetear, ui_event_ButtonResetear, LV_EVENT_ALL, NULL);

}
